import type { LinkedInGhostLife } from '@/lib/types'

export function buildLinkedInGhost(life: LinkedInGhostLife): string {
  const openToWorkBanner = life.openToWork
    ? `<div class="otw-banner">#OpenToWork</div>`
    : ''

  const jobs = life.jobs.map(job => `
    <div class="job">
      <div class="job-header">
        <div class="job-title">${esc(job.title)}</div>
        <div class="job-company">${esc(job.company)}</div>
        <div class="job-meta">${esc(job.dateRange)}</div>
      </div>
      <p class="job-desc">${esc(job.description)}</p>
    </div>
  `).join('')

  const endorsements = life.endorsements.map(e => `
    <div class="endorsement">
      <div class="endorser-name">${esc(e.name)}</div>
      <div class="endorser-title">${esc(e.title)}</div>
      <p class="endorsement-text">"${esc(e.text)}"</p>
    </div>
  `).join('')

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(life.name)} | LinkedIn</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    font-family: -apple-system, system-ui, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    background: #f3f2ef;
    color: rgba(0,0,0,0.9);
    font-size: 14px;
    line-height: 1.5;
    min-height: 100vh;
    padding: 24px 16px;
  }
  .card {
    background: #fff;
    border-radius: 8px;
    max-width: 680px;
    margin: 0 auto;
    overflow: hidden;
    border: 1px solid rgba(0,0,0,0.08);
  }
  .hero {
    background: #b6c1d0;
    height: 96px;
    position: relative;
  }
  .avatar {
    width: 80px; height: 80px;
    border-radius: 50%;
    background: #738ea5;
    border: 3px solid #fff;
    position: absolute;
    bottom: -24px;
    left: 20px;
    display: flex; align-items: center; justify-content: center;
    font-size: 28px; color: #fff; font-weight: 600;
  }
  .profile-body { padding: 32px 20px 20px; }
  .name { font-size: 22px; font-weight: 600; line-height: 1.2; margin-bottom: 4px; }
  .headline { font-size: 14px; color: rgba(0,0,0,0.75); margin-bottom: 4px; }
  .location { font-size: 12px; color: rgba(0,0,0,0.55); margin-bottom: 4px; }
  .connections { font-size: 12px; color: #0a66c2; margin-bottom: 16px; }
  .otw-banner {
    display: inline-block;
    background: #1c7a43;
    color: #fff;
    font-size: 11px;
    font-weight: 600;
    padding: 3px 10px;
    border-radius: 3px;
    margin-bottom: 16px;
  }
  .section { border-top: 6px solid #f3f2ef; padding: 16px 20px; }
  .section-title { font-size: 16px; font-weight: 600; margin-bottom: 14px; }
  .about p { font-size: 14px; color: rgba(0,0,0,0.8); margin-bottom: 10px; line-height: 1.6; }
  .job { margin-bottom: 20px; }
  .job-title { font-weight: 600; font-size: 14px; }
  .job-company { font-size: 13px; }
  .job-meta { font-size: 12px; color: rgba(0,0,0,0.55); margin: 2px 0 6px; }
  .job-desc { font-size: 13px; color: rgba(0,0,0,0.75); line-height: 1.5; }
  .endorsement { margin-bottom: 16px; padding-bottom: 16px; border-bottom: 1px solid rgba(0,0,0,0.08); }
  .endorsement:last-child { border-bottom: none; margin-bottom: 0; padding-bottom: 0; }
  .endorser-name { font-weight: 600; font-size: 13px; }
  .endorser-title { font-size: 12px; color: rgba(0,0,0,0.55); margin-bottom: 6px; }
  .endorsement-text { font-size: 13px; color: rgba(0,0,0,0.75); font-style: italic; line-height: 1.5; }
  .footer-note {
    text-align: center;
    font-size: 10px;
    color: rgba(0,0,0,0.35);
    padding: 12px;
    border-top: 1px solid rgba(0,0,0,0.06);
    letter-spacing: 0.03em;
  }
</style>
</head>
<body>
<div class="card">
  <div class="hero">
    <div class="avatar">${esc(life.name.charAt(0))}</div>
  </div>
  <div class="profile-body">
    ${openToWorkBanner}
    <div class="name">${esc(life.name)}</div>
    <div class="headline">${esc(life.headline)}</div>
    <div class="location">${esc(life.location)}</div>
    <div class="connections">500+ connections</div>
  </div>

  <div class="section about">
    <div class="section-title">About</div>
    <p>${esc(life.about[0])}</p>
    <p>${esc(life.about[1])}</p>
  </div>

  <div class="section">
    <div class="section-title">Experience</div>
    ${jobs}
  </div>

  <div class="section">
    <div class="section-title">Recommendations</div>
    ${endorsements}
  </div>

  <div class="footer-note">generated by Almost &mdash; the life you didn&rsquo;t quite live</div>
</div>
</body>
</html>`
}

function esc(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;')
}
