import type { WikiStubLife } from '@/lib/types'

export function buildWikiStub(life: WikiStubLife): string {
  const sections = [
    { title: 'Early life', content: life.sections.earlyLife },
    { title: 'Career', content: life.sections.career },
    { title: 'Personal life', content: life.sections.personalLife },
    { title: 'Controversies', content: life.sections.controversies },
  ]

  const citationLinks = life.citations.map(c =>
    `<li id="cite-${c.index}"><span class="cite-num">[${c.index}]</span> ${esc(c.text)}</li>`
  ).join('\n')

  const sectionHtml = sections.map(s => `
    <h2 class="section-title">${esc(s.title)}</h2>
    <p>${esc(s.content)}</p>
  `).join('')

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(life.name)} - Wikipedia</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    font-family: 'Linux Libertine', 'Georgia', 'Times', serif;
    background: #fff;
    color: #202122;
    font-size: 14px;
    line-height: 1.6;
    padding: 20px 16px;
  }
  .content { max-width: 960px; margin: 0 auto; }
  .stub-banner {
    background: #f8f9fa;
    border: 1px solid #a2a9b1;
    padding: 8px 12px;
    margin-bottom: 18px;
    font-size: 13px;
    display: flex;
    align-items: flex-start;
    gap: 10px;
  }
  .stub-icon { font-size: 20px; line-height: 1; flex-shrink: 0; }
  h1 {
    font-family: 'Linux Libertine', 'Georgia', serif;
    font-size: 28px;
    font-weight: normal;
    border-bottom: 1px solid #a2a9b1;
    padding-bottom: 4px;
    margin-bottom: 16px;
  }
  .intro { margin-bottom: 20px; }
  .intro p { margin-bottom: 10px; }
  sup { font-size: 10px; color: #0645ad; }
  .infobox {
    float: right;
    clear: right;
    margin: 0 0 16px 24px;
    border: 1px solid #a2a9b1;
    background: #f8f9fa;
    font-size: 13px;
    width: 260px;
  }
  .infobox-title {
    background: #cee0f2;
    text-align: center;
    font-weight: bold;
    padding: 6px;
    border-bottom: 1px solid #a2a9b1;
  }
  .infobox table { width: 100%; border-collapse: collapse; }
  .infobox td { padding: 4px 8px; vertical-align: top; border-bottom: 1px solid #eaecf0; }
  .infobox td:first-child { font-weight: bold; white-space: nowrap; }
  .section-title {
    font-family: 'Linux Libertine', 'Georgia', serif;
    font-size: 20px;
    font-weight: normal;
    border-bottom: 1px solid #a2a9b1;
    padding-bottom: 3px;
    margin: 20px 0 10px;
  }
  p { margin-bottom: 10px; }
  .references { margin-top: 24px; }
  .references h2 { font-size: 20px; font-weight: normal; border-bottom: 1px solid #a2a9b1; padding-bottom: 3px; margin-bottom: 10px; }
  .references ol { padding-left: 24px; }
  .references li { font-size: 13px; margin-bottom: 4px; }
  .cite-num { color: #0645ad; margin-right: 4px; }
  .clearfix::after { content: ''; display: table; clear: both; }
  .footer-note { margin-top: 24px; text-align: center; font-size: 10px; color: #72777d; border-top: 1px solid #a2a9b1; padding-top: 10px; font-family: sans-serif; }
</style>
</head>
<body>
<div class="content">
  <div class="stub-banner">
    <span class="stub-icon">📄</span>
    <span>This article is a <b>stub</b>. You can help Wikipedia by <a href="#">expanding it</a>.</span>
  </div>

  <div class="clearfix">
    <div class="infobox">
      <div class="infobox-title">${esc(life.name)}</div>
      <table>
        <tr><td>Born</td><td>${esc(life.infobox.born)}</td></tr>
        <tr><td>Nationality</td><td>${esc(life.infobox.nationality)}</td></tr>
        <tr><td>Occupation</td><td>${esc(life.infobox.occupation)}</td></tr>
        <tr><td>Known for</td><td>${esc(life.infobox.knownFor)}</td></tr>
      </table>
    </div>

    <h1>${esc(life.name)}</h1>
    <div class="intro">
      <p>${esc(life.intro)}</p>
    </div>

    ${sectionHtml}
  </div>

  <div class="references">
    <h2>References</h2>
    <ol>${citationLinks}</ol>
  </div>

  <div class="footer-note">generated by Almost &mdash; the life you didn&rsquo;t quite live</div>
</div>
</body>
</html>`
}

function esc(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;')
}
